"""Codebreakers: A modular Python cryptographic and cryptanalysis package."""

from codebreakers.application import CipherOperation, CipherRequest, CipherService
from codebreakers.domain import (
    Alphabet,
    AlphabetError,
    AmbiguousKeyError,
    AnalysisError,
    CaesarCipher,
    CaseStrategy,
    Cipher,
    CipherKeyError,
    CodebreakersError,
    DomainError,
    DuplicateKeyMappingError,
    DuplicateSymbolError,
    EmptyAlphabetError,
    HomophonicKey,
    HomophonicSubstitutionCipher,
    IncompleteKeyError,
    InsufficientTextError,
    InvalidKeyError,
    SubstitutionCipher,
    SubstitutionKey,
    SymbolNotFoundError,
    TransformOptions,
    UnknownSymbolError,
    UnknownSymbolStrategy,
    VigenereCipher,
    VigenereKey,
)

__version__ = "0.1.0"

__all__ = [
    "AmbiguousKeyError",
    "Alphabet",
    "AlphabetError",
    "AnalysisError",
    "CaesarCipher",
    "CaseStrategy",
    "Cipher",
    "CipherKeyError",
    "CipherOperation",
    "CipherRequest",
    "CipherService",
    "CodebreakersError",
    "DomainError",
    "DuplicateKeyMappingError",
    "DuplicateSymbolError",
    "EmptyAlphabetError",
    "HomophonicKey",
    "HomophonicSubstitutionCipher",
    "IncompleteKeyError",
    "InvalidKeyError",
    "InsufficientTextError",
    "SymbolNotFoundError",
    "SubstitutionCipher",
    "SubstitutionKey",
    "TransformOptions",
    "UnknownSymbolError",
    "UnknownSymbolStrategy",
    "VigenereCipher",
    "VigenereKey",
    "__version__",
]
